services:
  web:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    depends_on:
      - redis

  celery:
    build: .
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
    command: celery -A myproject worker --loglevel=info
    volumes:
      - .:/code
    depends_on:
      - redis

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
